app = "arkguess-server"
primary_region = "hkg"

[build]
  dockerfile = "server/Dockerfile"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "5s"
    method = "get"
    path = "/health"
    grace_period = "10s"
